---     #update remote system except kernel
- hosts: all
  connection: ssh
  become: yes
  become_method: sudo
  tasks:
    - name: Update remote system
      yum:
        name: "*"
        state: latest
#        exclude: kernel*
    - name: Reboot remote systems
      command: reboot
